version: "3.8"

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "asdf;lkj"
      MYSQL_DATABASE: todolist_db
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: mysql_volume
        target: /data/db
        read_only: false
    networks:
      - todolist_network
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 256M
        limits:
          cpus: "1.0"
          memory: 512M

volumes:
  mysql_volume:
    external: false

networks:
  todolist_network:
    driver: bridge
