version: "3.8"

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: "asdf;lkj"
      MYSQL_DATABASE: todolist_db
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: mysql_volume
        target: /data/db
        read_only: false
    networks:
      - todolist_network
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: 256M
        limits:
          cpus: "1.0"
          memory: 512M

volumes:
  mysql_volume:
    external: false

networks:
  todolist_network:
    driver: bridge

# .github/workflows/security.yml
# name: Security Pipeline

# on: [push, pull_request]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       # Unit & Integration Tests
#       - name: Run Tests
#         run: ./mvnw test

#       # SAST â€” Static Analysis Security Testing
#       - name: Run SpotBugs (Find Bugs)
#         run: ./mvnw spotbugs:check

#       # Dependency vulnerability scan
#       - name: OWASP Dependency Check
#         run: ./mvnw dependency-check:check

#       # Code quality
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarcloud-github-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
